repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check
        language: system
        files: \.(py|pyi)$
        args: [--fix]

      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        files: \.(py|pyi)$

      - id: pyrefly
        name: pyrefly
        entry: uv run pyrefly check
        language: system
        files: \.(py|pyi)$
